version: '3'
services:
  ais-api:
    build: .
    # image: redningsselskapet/rs-position-tracker
    networks: 
      - aisnet-backend
    ports: 
      - 3000:3000  
    environment:
      - ENABLE_API=false
      - ENABLE_AIS_COLLECTOR=false
      - AIS_DATA_PROVIDER_KYSTVERKET_ENABLED=false
      - AIS_DATA_PROVIDER_MARINE_TRAFFIC_ENABLED=false
      - AIS_DATA_PROVIDER_MARINE_TRAFFIC_API_KEY=c03c8a1570c13a6f3497d189adc9294c96e5b5fc
      - DB_URI=mongodb://mongodb-service:27017/positions
      - DB_USER=my_user
      - DB_PASSWORD=password123
    volumes:
      - ./src:/app/src
    restart: on-failure
    command: [ "node_modules/nodemon/bin/nodemon.js", "src/app.js"]
  mongodb-service:
    image: bitnami/mongodb
    environment:
      - MONGODB_ROOT_PASSWORD=secret
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=positions
    networks: 
      - aisnet-backend
    ports: 
      - 27017:27017
networks:
  aisnet-backend:

 